"""Native-typed default values for configuration keys that the code reads directly
but are **not** present in ``.env.example``.

Historically these keys resolved to the string ``"mock_value"`` (see the old
``Settings.__getattr__``), which silently broke every indicator, risk and
portfolio code path that expected an ``int`` window, a ``float`` ratio or a
``bool`` flag. This module supplies the real, conservative, research-only
defaults so the engines run correctly out of the box.

Resolution precedence in :mod:`bist_signal_bot.config.settings` is::

    os.environ  >  .env  >  .env.example  >  DEFAULTS (this file)  >  name-based guess

i.e. anything an operator sets in ``.env`` always wins; these values only fill
gaps. Standard technical-analysis window sizes are used where applicable.
"""
from __future__ import annotations

from typing import Any

DEFAULTS: dict[str, Any] = {
    # ---- Core application ----
    "APP_NAME": "bist-signal-bot",
    "APP_ENV": "development",
    "RUN_MODE": "research",
    "MARKET_TIMEZONE": "Europe/Istanbul",
    "DEFAULT_MARKET": "BIST",
    "DRY_RUN": True,
    "ENABLE_TELEGRAM": False,

    # ---- Adaptive engine ----
    "ADAPTIVE_DEFAULT_TOP_N": 5,
    "ADAPTIVE_MODE": "RECOMMEND_ONLY",
    "ADAPTIVE_SAVE_REPORTS": False,
    "ADAPTIVE_DIR_NAME": "adaptive",
    # AdaptivePolicy thresholds — mirror AdaptivePolicy model field defaults so
    # the policy builds cleanly from settings (override any of these in .env).
    "ADAPTIVE_MIN_EVIDENCE_COUNT": 2,
    "ADAPTIVE_MIN_BACKTEST_TRADES": 10,
    "ADAPTIVE_MIN_WALK_FORWARD_SPLITS": 3,
    "ADAPTIVE_MIN_OOS_POSITIVE_SPLIT_PCT": 50.0,
    "ADAPTIVE_MAX_ALLOWED_DRAWDOWN_PCT": 35.0,
    "ADAPTIVE_MIN_PROFIT_FACTOR": 1.0,
    "ADAPTIVE_MIN_SHARPE": -5.0,
    "ADAPTIVE_MIN_PAPER_TRADES": 5,
    "ADAPTIVE_MAX_RECENT_PAPER_DRAWDOWN_PCT": 20.0,
    "ADAPTIVE_MAX_MODEL_AGE_DAYS": 30,
    "ADAPTIVE_MIN_ML_SCORE": 50.0,
    "ADAPTIVE_REQUIRE_REGIME_MATCH": False,
    "ADAPTIVE_REJECT_HIGH_OVERFIT_WARNING": True,
    "ADAPTIVE_AUTO_APPLY_REQUIRES_CONFIRM": True,

    # ---- Momentum indicators (standard TA windows) ----
    "MOMENTUM_RSI_WINDOW": 14,
    "MOMENTUM_ROC_WINDOW": 12,
    "MOMENTUM_TSI_SLOW": 25,
    "MOMENTUM_TSI_FAST": 13,
    "MOMENTUM_TSI_SIGNAL": 7,
    "MOMENTUM_PPO_FAST": 12,
    "MOMENTUM_PPO_SLOW": 26,
    "MOMENTUM_PPO_SIGNAL": 9,
    "MOMENTUM_ULTIMATE_SHORT": 7,
    "MOMENTUM_ULTIMATE_MEDIUM": 14,
    "MOMENTUM_ULTIMATE_LONG": 28,
    "MOMENTUM_CCI_WINDOW": 20,
    "MOMENTUM_MFI_WINDOW": 14,
    "MOMENTUM_STOCH_K_WINDOW": 14,
    "MOMENTUM_STOCH_D_WINDOW": 3,
    "MOMENTUM_WILLIAMS_WINDOW": 14,

    # ---- Trend indicators ----
    "TREND_SHORT_WINDOW": 20,
    "TREND_MEDIUM_WINDOW": 50,
    "TREND_LONG_WINDOW": 200,
    "TREND_ADX_WINDOW": 14,
    "TREND_AROON_WINDOW": 25,
    "TREND_ATR_WINDOW": 14,
    "TREND_DONCHIAN_WINDOW": 20,
    "TREND_KELTNER_EMA_WINDOW": 20,
    "TREND_LINREG_WINDOW": 20,
    "TREND_SUPERTREND_ATR_WINDOW": 10,

    # ---- Volume indicators ----
    "VOLUME_WINDOW": 20,
    "VOLUME_CMF_WINDOW": 20,
    "VOLUME_EOM_WINDOW": 14,
    "VOLUME_LIQUIDITY_WINDOW": 20,
    "VOLUME_PRICE_WINDOW": 20,
    "VOLUME_MIN_TURNOVER_TRY": 1_000_000.0,

    # ---- Volatility indicators ----
    "VOL_WINDOW": 20,
    "VOL_ATR_WINDOW": 14,
    "VOL_BB_WINDOW": 20,
    "VOL_BB_STD": 2.0,
    "VOL_GAP_WINDOW": 20,
    "VOL_RANGE_WINDOW": 20,
    "VOL_RANK_WINDOW": 252,
    "VOL_REGIME_RANK_WINDOW": 252,
    "VOL_Z_WINDOW": 20,
    "VOL_ANNUALIZATION": 252.0,

    # ---- Market regime analysis ----
    "REGIME_TREND_WINDOW": 50,
    "REGIME_VOLATILITY_WINDOW": 20,
    "REGIME_MOMENTUM_WINDOW": 20,
    "REGIME_LIQUIDITY_WINDOW": 20,
    "REGIME_CORRELATION_WINDOW": 60,
    "REGIME_USE_MTF": False,
    "REGIME_USE_BENCHMARK_RELATIVE": False,
    "REGIME_SCORE_MODE": "FILTER_AND_SCORE",
    "REGIME_MIN_SCORE": 40.0,
    "REGIME_REJECT_STRESS": False,
    "REGIME_REDUCE_IN_STRESS": True,
    "REGIME_STRESS_REDUCTION_FACTOR": 0.50,

    # ---- Candlestick / chart patterns ----
    "PATTERN_BREAKOUT_WINDOW": 20,
    "PATTERN_RANGE_WINDOW": 20,
    "PATTERN_SR_WINDOW": 20,
    "PATTERN_VOLUME_WINDOW": 20,
    "PATTERN_DOJI_BODY_THRESHOLD": 0.1,
    "PATTERN_GAP_THRESHOLD": 0.02,
    "PATTERN_SR_TOLERANCE_PCT": 0.02,
    "PATTERN_FEATURE_LEVEL": "STANDARD",

    # ---- Divergence detection ----
    "DIVERGENCE_MIN_PIVOT_DISTANCE": 5,
    "DIVERGENCE_MAX_PIVOT_DISTANCE": 60,
    "DIVERGENCE_MIN_STRENGTH_SCORE": 0.5,
    "DIVERGENCE_PIVOT_MODE": "LOOKBACK_ONLY",
    "DIVERGENCE_DEFAULT_INDICATORS": "rsi,macd_hist,obv,mfi",
    "DIVERGENCE_LOOKBACK": 5,
    "DIVERGENCE_CONFIRMATION_BARS": 3,
    "DIVERGENCE_INCLUDE_HIDDEN": True,
    "DIVERGENCE_INCLUDE_REGULAR": True,

    # ---- Risk engine (conservative, research defaults) ----
    "RISK_PER_TRADE_PCT": 0.01,
    "RISK_EQUITY_POSITION_PCT": 0.10,
    "RISK_DEFAULT_EQUITY": 100_000.0,
    "RISK_DEFAULT_AVAILABLE_CASH": 100_000.0,
    "RISK_POSITION_SIZING_METHOD": "EQUITY_PERCENT",
    "RISK_USE_FRACTIONAL_SHARES": False,
    "RISK_ALLOW_SHORT": False,
    "RISK_ALLOW_SAME_SYMBOL_POSITION": False,
    "RISK_REJECT_IF_NO_STOP": False,
    "RISK_REJECT_IF_NO_TARGET": False,
    "RISK_STOP_METHOD": "FIXED_PERCENT",
    "RISK_TARGET_METHOD": "RISK_REWARD_MULTIPLE",
    "RISK_TARGET_R_MULTIPLE": 2.0,
    "RISK_ATR_MULTIPLIER": 2.0,
    "RISK_SWING_LOOKBACK": 20,
    "RISK_FIXED_STOP_PCT": 0.05,
    "RISK_FIXED_TARGET_PCT": 0.10,
    "RISK_FIXED_NOTIONAL": 10_000.0,
    "RISK_MAX_ATR_PCT": 0.10,
    "RISK_MAX_COST_BPS": 50.0,
    "RISK_MAX_DAILY_SIGNALS": 20,
    "RISK_MAX_DAILY_LOSS_PCT": 2.0,          # daily-loss guard: halt new entries at -2% of start-of-day equity
    "RISK_MAX_CONSECUTIVE_LOSSES": 6,
    "RISK_MAX_DRAWDOWN_PCT": 8.0,            # trailing drawdown from rolling equity peak; needs explicit reset
    "RISK_BLOCK_AUCTION_ENTRIES": True,
    "RISK_MIN_EDGE_TO_COST_RATIO": 1.5,
    "RISK_MAX_OPEN_POSITIONS": 8,
    "RISK_MAX_PORTFOLIO_RISK_PCT": 0.20,
    "RISK_MAX_POSITION_SIZE_PCT": 0.20,
    "RISK_MAX_VOLATILITY_PCT": 0.50,
    "RISK_MIN_AVG_TURNOVER_TRY": 1_000_000.0,
    "RISK_MIN_CONFIDENCE": 0.50,
    "RISK_MIN_RISK_REWARD": 1.5,
    "RISK_MIN_SIGNAL_SCORE": 0.50,
    "RISK_MIN_TRADE_NOTIONAL": 1_000.0,
    # ---- Intraday sizing / portfolio limits (risk/sizing_intraday.py, portfolio_limits.py) ----
    "RISK_TARGET_VOL_ANNUAL": 0.15,
    "RISK_KELLY_FRACTION": 0.25,
    "RISK_KELLY_CAP": 0.10,
    "RISK_KELLY_PRIOR_STRENGTH": 200,
    "RISK_MAX_RISK_PER_TRADE_BPS": 25.0,
    "RISK_MAX_POSITION_PCT": 0.10,
    "RISK_MAX_GROSS_EXPOSURE_PCT": 1.0,
    "RISK_MAX_SECTOR_PCT": 0.30,
    "RISK_CORR_THRESHOLD": 0.8,
    "RISK_MAX_CLUSTER_PCT": 0.25,
    "RISK_MAX_DAILY_TURNOVER_PCT": 2.0,
    "RISK_MIN_ADV_TRY": 5_000_000.0,
    "RISK_MAX_SPREAD_BPS": 40.0,
    "RISK_LOT_SIZE": 1,
    "RISK_MAX_PARTICIPATION": 0.05,
    "RISK_KELLY_REQUIRED": False,
    "RISK_MAX_LEVERAGE": 1.0,

    # ---- Portfolio construction ----
    "PORTFOLIO_DEFAULT_NOTIONAL": 100_000.0,
    "PORTFOLIO_MAX_CORRELATION_CLUSTER_WEIGHT": 0.40,
    "PORTFOLIO_MAX_COST_DRAG_BPS": 50.0,
    "PORTFOLIO_MAX_GROSS_EXPOSURE_PCT": 1.0,
    "PORTFOLIO_MAX_NET_EXPOSURE_PCT": 1.0,
    "PORTFOLIO_MAX_OPEN_POSITIONS": 8,
    "PORTFOLIO_MAX_POSITIONS": 10,
    "PORTFOLIO_MAX_SECTOR_WEIGHT": 0.30,
    "PORTFOLIO_MAX_SECTOR_WEIGHT_PCT": 0.30,
    "PORTFOLIO_MAX_SYMBOL_WEIGHT": 0.20,
    "PORTFOLIO_MAX_SYMBOL_WEIGHT_PCT": 0.20,
    "PORTFOLIO_MIN_CASH_PCT": 0.05,
    "PORTFOLIO_REBALANCE_MIN_DELTA_WEIGHT": 0.01,
    "PORTFOLIO_MIN_DIVERSIFICATION_SCORE": 50.0,
    "PORTFOLIO_MAX_TURNOVER_PCT": 50.0,
    "PORTFOLIO_HIGH_CORRELATION_THRESHOLD": 0.75,
    "PORTFOLIO_CONSTRUCTION_SAVE_RESULTS": True,
    "PORTFOLIO_CONSTRUCTION_RESEARCH_ONLY": True,
    "PORTFOLIO_TOTAL_ALLOCATION_PCT": 0.95,
    "PORTFOLIO_USE_CALIBRATED_CONFIDENCE": False,
    "PORTFOLIO_USE_MONTE_CARLO_SCORE": False,

    # ---- Backtest ----
    "BACKTEST_MAX_POSITION_SIZE_PCT": 0.20,
    "BACKTEST_MIN_TRADE_NOTIONAL": 1_000.0,
    "BACKTEST_PERIODS_PER_YEAR": 252,
    "BACKTEST_EXECUTION_PRICE_MODE": "SAME_CLOSE_FOR_RESEARCH_ONLY",
    "BACKTEST_COST_SCENARIO": "BASE",

    # ---- Calibration ----
    "CALIBRATION_MIN_RECORDS": 30,
    "CALIBRATION_MIN_COHORT_SAMPLES": 10,
    "CALIBRATION_SUCCESS_RETURN_PCT": 0.05,
    "CALIBRATION_FAILURE_RETURN_PCT": -0.05,

    # ---- Data cleaning ----
    "CLEANING_MISSING_VALUE_POLICY": "FORWARD_FILL",
    "CLEANING_INVALID_OHLC_POLICY": "DROP_ROW",
    "CLEANING_OUTLIER_POLICY": "FLAG_ONLY",
    "CLEANING_DUPLICATE_TIMESTAMP_POLICY": "KEEP_LAST",
    "CLEANING_STRICT": False,
    "CLEANING_FAIL_ON_ERROR": False,
    "CLEANING_MAX_DAILY_RETURN_ABS": 0.35,
    "CLEANING_MAX_VOLUME_ZSCORE": 10.0,
    "CLEANING_MIN_ROWS_AFTER_CLEANING": 100,

    # ---- Drift / Monte Carlo / Stress ----
    "DRIFT_MIN_SAMPLES": 30,
    "DRIFT_ECE_WARN": 0.05,
    "DRIFT_ECE_FAIL": 0.10,
    "DRIFT_BRIER_WARN": 0.25,
    "MONTE_CARLO_DRAWDOWN_THRESHOLD_PCT": 0.20,
    "MONTE_CARLO_REALITY_PVALUE_WARN": 0.05,
    "MONTE_CARLO_REALITY_PVALUE_FAIL": 0.20,
    "MONTE_CARLO_MULTIPLE_TESTING_TRIALS_WARN": 20,
    "STRESS_RUIN_THRESHOLD_PCT": 0.50,

    # ---- Leaderboard scoring ----
    "LEADERBOARD_RESEARCH_ONLY": True,
    "LEADERBOARD_MIN_CANDIDATES": 1,
    "LEADERBOARD_SCORE_PASS_THRESHOLD": 70.0,
    "LEADERBOARD_SCORE_WATCH_THRESHOLD": 50.0,
    "LEADERBOARD_SCORE_FAIL_THRESHOLD": 30.0,
    "LEADERBOARD_SELECTION_MIN_SAMPLE": 30,
    "LEADERBOARD_SELECTION_MIN_SCORE": 50.0,
    "LEADERBOARD_WEIGHT_CALIBRATION_SCORE": 0.33,
    "LEADERBOARD_WEIGHT_ROBUSTNESS_SCORE": 0.33,
    "LEADERBOARD_WEIGHT_VALIDATION_SCORE": 0.34,
    "LEADERBOARD_WEIGHT_MONITORING_HEALTH": 0.0,
    "LEADERBOARD_WEIGHT_FEATURE_QUALITY": 0.0,
    "LEADERBOARD_WEIGHT_MODEL_GOVERNANCE": 0.0,
    "LEADERBOARD_WEIGHT_CONTEXT_SUPPORT": 0.0,
    "LEADERBOARD_WEIGHT_REVIEW_BURDEN": 0.0,
    "LEADERBOARD_WEIGHT_DATA_QUALITY": 0.0,
    "LEADERBOARD_LOW_SAMPLE_PENALTY": 10.0,
    "LEADERBOARD_LEAKAGE_PENALTY": 30.0,
    "LEADERBOARD_SELECTION_BLOCK_ON_LEAKAGE": True,
    "LEADERBOARD_SELECTION_BLOCK_ON_GOVERNANCE_FAIL": True,
    "LEADERBOARD_DEFAULT_STRATEGY_COHORT": True,
    "LEADERBOARD_DEFAULT_MODEL_COHORT": True,
    "LEADERBOARD_DEFAULT_FEATURE_SET_COHORT": True,

    # ---- Knowledge memory ----
    "KNOWLEDGE_HYBRID_EMBEDDING_WEIGHT": 0.5,
    "KNOWLEDGE_HYBRID_KEYWORD_WEIGHT": 0.5,
    "KNOWLEDGE_MEMORY_MIN_CASES": 1,

    # ---- Runtime loop / jobs ----
    "RUNTIME_DEFAULT_TOP_N": 10,
    "RUNTIME_DEFAULT_STRATEGY": "moving_average_trend",
    "RUNTIME_DEFAULT_SOURCE": "local",  # validate_pipeline_config accepts 'mock' or 'local'
    "RUNTIME_REPORT_FORMATS": "md",
    "RUNTIME_USE_TRADE_RISK": True,
    "RUNTIME_USE_PORTFOLIO_RISK": True,
    "RUNTIME_USE_ML_FILTER": False,       # enable once a model is trained/registered
    "RUNTIME_USE_DECISION_LAYER": False,  # consult risk guard (daily loss/kill switch) before PAPER_RUN; off = legacy behaviour
    "RUNTIME_USE_REGIME_FILTER": True,
    "RUNTIME_RUN_DRIFT_CHECK": False,     # enable once a baseline model exists
    "RUNTIME_JOB_MAX_RETRIES": 2,
    "RUNTIME_JOB_RETRY_DELAY_SECONDS": 5,
    "RUNTIME_JOB_TIMEOUT_SECONDS": 300,
    "RUNTIME_LOCK_TTL_SECONDS": 3600,
    "RUNTIME_RUN_IMMEDIATELY": True,
    "RUNTIME_STOP_ON_FAILURE": False,
    "RUNTIME_MAX_ITERATIONS": 1,
    "RUNTIME_SLEEP_SECONDS": 60,
    "RUNTIME_UNIVERSE_MODE": "ALL",  # scan the whole seed universe (ScanUniverseMode has no FILE)
    "RUNTIME_SESSION_POLICY": "RUN_ALWAYS",  # research-friendly; use ONLY_AFTER_CLOSE in production
    "RUNTIME_LOCK_FILE_NAME": "runtime.lock",
    "RUNTIME_STATE_FILE_NAME": "runtime_state.json",

    # ---- Telegram throttling ----
    "TELEGRAM_ERROR_COOLDOWN_SECONDS": 300,
    "TELEGRAM_RATE_LIMIT_SECONDS": 1,
    "TELEGRAM_SEND_TIMEOUT_SECONDS": 10,
    "TELEGRAM_CENTER_DIR_NAME": "telegram",

    # ---- Misc engine modes / strategies ----
    "DEFAULT_STRATEGY": "moving_average_trend",
    "STRATEGY_CANDIDATE_DISCLAIMER": (
        "Research signal candidate only. Not investment advice. No real order sent."
    ),
    "DOWNLOAD_DEFAULT_PERIOD": "2y",
    "ENSEMBLE_WEIGHT_STRATEGY": "EQUAL",
    "MTF_ALIGNMENT_MODE": "CLOSED_BAR_ONLY",
    "MTF_BASE_TIMEFRAME": "1d",
    "MTF_HIGHER_TIMEFRAMES": "1wk,1mo",
    "MTF_FORWARD_FILL": True,
    "MTF_SHIFT_HIGHER_TF_BY_ONE_BAR": True,
    "MTF_PREFIX_COLUMNS": True,
    "MTF_DROP_UNALIGNED_ROWS": False,
    "MTF_DROP_INCOMPLETE_HIGHER_TF_BAR": True,
    "PAPER_EXECUTION_MODE": "CLOSE",
    "PAPER_DEFAULT_ACCOUNT_ID": "default",
    "PAPER_INITIAL_CASH": 100000.0,
    "PAPER_CASH_INTEREST_ANNUAL": 0.30,  # PLACEHOLDER idle-cash yield (TL deposit/repo); unverified - set to your real rate
    "PAPER_CASH_INTEREST_WITHHOLDING": 0.15,  # PLACEHOLDER stopaj on interest; unverified
    "BACKTEST_CASH_INTEREST_ENABLED": True,  # idle cash earns interest in backtests (same formula as paper ledger)
    "BACKTEST_CASH_INTEREST_ANNUAL": 0.30,  # keep equal to PAPER_CASH_INTEREST_ANNUAL (placeholder, unverified)
    "BACKTEST_CASH_INTEREST_WITHHOLDING": 0.15,  # keep equal to PAPER_CASH_INTEREST_WITHHOLDING (placeholder)
    "ERROR_NOTIFICATION_MIN_LEVEL": "ERROR",
    "SECURITY_REDACT_AUDIT": True,  # redact secrets from audit metadata (security)
    "ENABLE_PERFORMANCE_PROFILING": False,  # opt-in; profiler is heavy and off by default
    "DEPLOYMENT_DOCTOR_MIN_FREE_DISK_MB": 500,
    "QA_SYNTHETIC_PERIODS": 252,
    "PACKAGING_EXCLUDE_ENV_FILE": True,
    "PACKAGING_EXCLUDE_DATA_DIR": True,
    "PACKAGING_EXCLUDE_LOGS_DIR": True,
    "PACKAGING_EXCLUDE_REPORTS_DIR": True,

    # ---- Storage layout: files ----
    "LOG_FILE_NAME": "bist_signal_bot.log",
    "MARKET_DATA_INDEX_FILE": "market_data_index.json",
    "CORPORATE_ACTIONS_FILE_NAME": "corporate_actions.csv",

    # ---- Directory names (storage layout) ----
    "LOG_DIR": "logs",
    "BOOTSTRAP_DIR_NAME": "bootstrap",
    "DATA_IMPORT_DIR_NAME": "imports",
    "FINANCIALS_DIR_NAME": "financials",
    "LEADERBOARD_DIR_NAME": "leaderboard",
    "MACRO_DIR_NAME": "macro",
    "ML_MODELS_DIR_NAME": "ml_models",
    "ML_TRAINING_DIR_NAME": "ml_training",
    "OHLCV_DIR_NAME": "ohlcv",
    "OPS_DIR_NAME": "ops",
    "PAPER_ACCOUNTS_DIR_NAME": "paper_accounts",
    "UNIVERSE_DIR_NAME": "universe",
    "UNIVERSE_SNAPSHOTS_DIR_NAME": "universe_snapshots",
    "UNIVERSE_FILE_NAME": "universe.csv",
    "WATCHLISTS_DIR_NAME": "watchlists",
    "MARKET_DATA_DIR_NAME": "market_data",
    "METADATA_DIR_NAME": "metadata",
    "CALIBRATION_DIR_NAME": "calibration",
    "DATA_LINEAGE_DIR_NAME": "lineage",
    "DATA_PROVIDER_HEALTH_DIR_NAME": "provider_health",
    "DRIFT_DIR_NAME": "drift",
    "FINAL_AUDIT_DIR_NAME": "final_audit",
    "GOVERNANCE_DIR_NAME": "governance",
    "MONTE_CARLO_DIR_NAME": "monte_carlo",
    "OPTIMIZATION_RESULTS_DIR_NAME": "optimization",
    "PORTFOLIO_CONSTRUCTION_DIR_NAME": "portfolio_construction",
    "SCENARIOS_DIR_NAME": "scenarios",
    "STRATEGY_REGISTRY_DIR_NAME": "strategy_registry",
    "WHATIF_DIR_NAME": "whatif",

    # ---- Harvested from inline getattr(settings, KEY, default) call sites ----
    # Settings never raises AttributeError, so those inline defaults were bypassed.
    # Conflicting sites (ENABLE_EVENT_CALENDAR/FEATURE_STORE, ENSEMBLE_INCLUDE_*) keep
    # the behaviour that was effectively in force before this block existed.
    "ALLOW_BROKER": False,
    "BACKTEST_HIGH_DRAWDOWN_WARNING_PCT": 30.0,
    "BACKTEST_MIN_TRADES_WARNING": 5,
    "BACKTEST_RISK_FREE_RATE": 0.0,
    "BACKUP_BEFORE_HEAVY_RESEARCH": False,
    "BACKUP_DIR_NAME": 'backups',
    "BASE_DIR": '.',
    "BIST_BOT_ENV": '',
    "BREADTH_WEIGHT_ABSOLUTE_MOMENTUM": 0.2,
    "BREADTH_WEIGHT_BREADTH_ALIGNMENT": 0.15,
    "BREADTH_WEIGHT_FUNDAMENTAL": 0.1,
    "BREADTH_WEIGHT_LIQUIDITY": 0.1,
    "BREADTH_WEIGHT_RELATIVE_STRENGTH": 0.45,
    "CALIBRATION_ECE_FAIL": 0.2,
    "CALIBRATION_ECE_WARN": 0.1,
    "CALIBRATION_MCE_FAIL": 0.35,
    "CALIBRATION_MCE_WARN": 0.2,
    "CALIBRATION_MERGE_SPARSE_BINS": True,
    "CALIBRATION_MIN_BIN_SAMPLES": 10,
    "CALIBRATION_USE_NET_RETURN_FOR_LABEL": True,
    "CLEANUP_DELETE_MARKET_DATA_DEFAULT": False,
    "CLEANUP_DELETE_RESEARCH_LEDGER_DEFAULT": False,
    "CLI_ALIAS_PREFIX": 'bt',
    "CLI_JSON_SORT_KEYS": True,
    "CONFIG_REGISTRY_WARN_UNKNOWN_ENV": False,
    "DATA_COMPARE_CLOSE_TOLERANCE_PCT": 0.1,
    "DATA_COMPARE_VOLUME_TOLERANCE_PCT": 5.0,
    "DATA_IMPORTS_DIR_NAME": 'imports',
    "DATA_IMPORT_CHUNKING_ENABLED": True,
    "DATA_IMPORT_CHUNK_SIZE": 50000,
    "DATA_IMPORT_DEDUPLICATE": True,
    "DATA_IMPORT_DROP_INVALID_REQUIRED_ROWS": True,
    "DATA_IMPORT_FAIL_ON_MISSING_REQUIRED": True,
    "DATA_IMPORT_NORMALIZE_DATES": True,
    "DATA_IMPORT_NORMALIZE_DECIMAL_COMMA": True,
    "DATA_IMPORT_NORMALIZE_SYMBOLS": True,
    "DATA_IMPORT_REGISTER_CATALOG_REQUIRES_CONFIRM": True,
    "DATA_IMPORT_ROW_COUNT_ESTIMATE": True,
    "DATA_IMPORT_SAVE_RESULTS": True,
    "DATA_IMPORT_WRITE_REQUIRES_CONFIRM": True,
    "DATA_YFINANCE_SUFFIX": '.IS',
    "DEFAULT_BENCHMARKS": 'buy_and_hold,moving_average_benchmark,naive_momentum,naive_volatility_filter',
    "DEPLOYMENT_DOCTOR_CHECK_IMPORTS": True,
    "DEPLOYMENT_DOCTOR_CHECK_PERMISSIONS": True,
    "DEPLOYMENT_DOCTOR_CHECK_SECRETS": True,
    "DEPLOYMENT_DOCTOR_CHECK_TIMEZONE": True,
    "DEPLOYMENT_SMOKE_TIMEOUT_SECONDS": 30,
    "DISCLOSURE_AUTO_CLASSIFY_ON_IMPORT": True,
    "DISCLOSURE_AUTO_EXTRACT_EVENTS_ON_IMPORT": True,
    "DISCLOSURE_AUTO_LINK_ENTITIES_ON_IMPORT": True,
    "DISCLOSURE_AUTO_NORMALIZE_ON_IMPORT": True,
    "DISCLOSURE_AUTO_TAG_RISKS_ON_IMPORT": True,
    "DISCLOSURE_CONFIDENCE_ADJUSTMENT_HIGH": -12.0,
    "DISCLOSURE_CONFIDENCE_ADJUSTMENT_REVIEW": -7.0,
    "DISCLOSURE_CONFIDENCE_ADJUSTMENT_WARN": -3.0,
    "DISCLOSURE_DIGEST_MAX_BODY_CHARS": 1500,
    "DISCLOSURE_DIGEST_MAX_RECORDS": 50,
    "DISCLOSURE_RISK_SCORE_HIGH": 80.0,
    "DISCLOSURE_RISK_SCORE_REVIEW": 65.0,
    "DISCLOSURE_RISK_SCORE_WARN": 40.0,
    "ENABLE_DISCLOSURE_INTELLIGENCE": True,
    "ENABLE_EVENT_CALENDAR": True,
    "ENABLE_FEATURE_STORE": True,
    "ENABLE_LOCAL_UI": True,
    "ENABLE_MONITORING": False,
    "ENABLE_PORTFOLIO_LEDGER": True,
    "ENABLE_PORTFOLIO_RESEARCH": False,
    "ENABLE_REAL_ORDERS": False,
    "ENSEMBLE_DEFAULT_MODE": 'METADATA_ONLY',
    "ENSEMBLE_DEFAULT_STRATEGIES": '',
    "ENSEMBLE_DIR_NAME": 'ensemble',
    "ENSEMBLE_HIGH_CONFLICT_SCORE": 60.0,
    "ENSEMBLE_INCLUDE_ADAPTIVE": False,
    "ENSEMBLE_INCLUDE_BREADTH": False,
    "ENSEMBLE_INCLUDE_FUNDAMENTALS": False,
    "ENSEMBLE_INCLUDE_ML": False,
    "ENSEMBLE_INCLUDE_REGIME": False,
    "ENSEMBLE_INCLUDE_RISK": False,
    "ENSEMBLE_MAX_CONFLICT_SCORE": 35.0,
    "ENSEMBLE_MIN_AGREEMENT_RATIO": 0.6,
    "ENSEMBLE_MIN_APPROVED_CONFIDENCE": 55.0,
    "ENSEMBLE_MIN_APPROVED_SCORE": 70.0,
    "ENSEMBLE_SAVE_OUTPUTS": False,
    "EVENTS_DIR_NAME": 'events',
    "EVENT_CONFIDENCE_ADJUSTMENT_WARN": -5.0,
    "EVENT_EXECUTION_SLIPPAGE_MULTIPLIER": 1.25,
    "EVENT_EXECUTION_SPREAD_MULTIPLIER": 1.2,
    "EXECUTION_ALLOW_PARTIAL_FILL": True,
    "EXECUTION_FIXED_SLIPPAGE_BPS": 10.0,
    "EXECUTION_INCLUDE_MARKET_IMPACT": True,
    "EXECUTION_INCLUDE_SLIPPAGE_COST": True,
    "EXECUTION_INCLUDE_SPREAD_COST": True,
    "EXECUTION_LIQUIDITY_FAIL_PARTICIPATION_PCT": 10.0,
    "EXECUTION_LIQUIDITY_WARN_PARTICIPATION_PCT": 3.0,
    "EXECUTION_LIQUIDITY_WINDOW": 20,
    "EXECUTION_MAX_PARTICIPATION_PCT": 5.0,
    "EXECUTION_MAX_SLIPPAGE_BPS": 250.0,
    "EXECUTION_MIN_AVERAGE_TURNOVER": 0.0,
    "EXECUTION_MIN_FILL_PROBABILITY": 0.1,
    "EXECUTION_NO_FILL_BELOW_PROBABILITY": 0.15,
    "EXECUTION_SIM_DIR_NAME": 'execution_sim',
    "EXECUTION_SLIPPAGE_MODEL": 'HYBRID',
    "EXECUTION_SPREAD_BPS_FALLBACK": 15.0,
    "EXECUTION_VOLUME_PARTICIPATION_MULTIPLIER": 0.25,
    "EXPLAINABILITY_DEFAULT_SEED": 42,
    "FEATURE_STORE_DIR_NAME": 'feature_store',
    "FINAL_RELEASE_INCLUDE_CHECKSUMS": True,
    "FINANCIAL_HIGH_DEBT_TO_EQUITY_WARN": 2.0,
    "FINANCIAL_QUALITY_STRONG_SCORE": 70.0,
    "FINANCIAL_QUALITY_WEAK_SCORE": 40.0,
    "FINANCIAL_RATIO_MIN_DENOMINATOR_ABS": 1e-09,
    "GOVERNANCE_BLOCK_BROKER_API": True,
    "GOVERNANCE_BLOCK_HTML_SCRAPING": True,
    "GOVERNANCE_BLOCK_PAID_SERVICES": True,
    "GOVERNANCE_BLOCK_REAL_ORDER_LANGUAGE": True,
    "GOVERNANCE_REQUIRE_CONFIRM_FOR_POLICY_UPDATE": True,
    "GOVERNANCE_REQUIRE_RESEARCH_ONLY": True,
    "GOVERNANCE_REQUIRE_SECRET_REDACTION": True,
    "GOVERNANCE_WARN_ON_MISSING_DISCLAIMER": True,
    "INDICATOR_CONTINUE_ON_ERROR": True,
    "INDICATOR_DEFAULT_SET": 'sma_20,sma_50,ema_20,rsi_14,atr_14,macd,bb_20,obv,return_1,volatility_20',
    "LOCAL_UI_ALLOW_CURSES": False,
    "LOCAL_UI_ALLOW_RICH": True,
    "LOCAL_UI_ALLOW_TEXTUAL": False,
    "LOCAL_UI_BACKEND": 'AUTO',
    "LOCAL_UI_BLOCK_BROKER_TERMS": True,
    "LOCAL_UI_BLOCK_ORDER_TERMS": True,
    "LOCAL_UI_BLOCK_UNSAFE_COMMANDS": True,
    "LOCAL_UI_BLOCK_WRITE_ACTIONS": True,
    "LOCAL_UI_DIR_NAME": 'local_ui',
    "LOCAL_UI_FALLBACK_TO_PLAIN_TEXT": True,
    "LOCAL_UI_MAX_TABLE_ROWS": 20,
    "LOCAL_UI_MAX_TEXT_CHARS": 5000,
    "LOCAL_UI_REQUIRE_TTY": False,
    "LOCAL_UI_SAFE_LANGUAGE_REQUIRED": True,
    "LOCAL_UI_SECRET_REDACTION_ENABLED": True,
    "LOCAL_UI_TRUNCATE_LONG_TEXT": True,
    "MAINTENANCE_DIR_NAME": 'maintenance',
    "MAINTENANCE_DOCTOR_BEFORE_RUN": False,
    "MIGRATION_REQUIRE_BACKUP": True,
    "ML_DEFAULT_FEATURE_LEVEL": 'FULL',
    "ML_DEFAULT_ROWS": 500,
    "ML_DEFAULT_SOURCE": 'mock',
    "ML_DEFAULT_TASK_TYPE": 'CLASSIFICATION',
    "ML_DEFAULT_TIMEFRAME": '1d',
    "ML_DROP_NA_FEATURES": False,
    "ML_DROP_NA_LABELS": True,
    "ML_FEATURE_STORE_DIR_NAME": 'ml/features',
    "ML_FILL_METHOD": 'median',
    "ML_INCLUDE_DIVERGENCE": True,
    "ML_INCLUDE_MOMENTUM": True,
    "ML_INCLUDE_MTF": False,
    "ML_INCLUDE_PATTERNS": True,
    "ML_INCLUDE_RAW_OHLCV": False,
    "ML_INCLUDE_RETURNS": True,
    "ML_INCLUDE_TREND": True,
    "ML_INCLUDE_VOLATILITY": True,
    "ML_INCLUDE_VOLUME": True,
    "ML_LABEL_COST_ADJUST": False,
    "ML_LABEL_HORIZON_BARS": 5,
    "ML_LABEL_NEGATIVE_THRESHOLD": -0.02,
    "ML_LABEL_NEUTRAL_CLASS_ENABLED": True,
    "ML_LABEL_POSITIVE_THRESHOLD": 0.02,
    "ML_LABEL_TYPE": 'BINARY_DIRECTION',
    "ML_LABEL_VOLATILITY_ADJUST": False,
    "ML_MAX_MISSING_FEATURE_PCT": 0.5,
    "ML_PREDICTION_LATEST_ONLY": True,
    "ML_PREDICTION_MAX_ROWS": 50,
    "ML_REMOVE_INF": True,
    "ML_ROBUST_SCALE": False,
    "ML_SAVE_DATASET": False,
    "ML_SPLIT_MODE": 'TRAIN_TEST',
    "ML_STANDARDIZE": False,
    "ML_WINSORIZE": False,
    "ML_WINSORIZE_LOWER_PCT": 0.01,
    "ML_WINSORIZE_UPPER_PCT": 0.99,
    "MODEL_ARTIFACT_ALLOWED_FORMATS": 'JSON,JOBLIB,PICKLE,SKLEARN,TEXT,DIRECTORY',
    "MODEL_CALIBRATION_DECAY_WARN": 0.05,
    "MODEL_CALIBRATION_MAX_ECE_WARN": 0.15,
    "MODEL_DRIFT_SCORE_WARN": 60.0,
    "MODEL_PERFORMANCE_DECAY_WARN": 0.1,
    "MODEL_PROMOTION_BLOCK_ON_MISSING_ARTIFACT": True,
    "MODEL_PROMOTION_BLOCK_ON_MISSING_CARD": True,
    "MODEL_VALIDATION_MIN_WALK_FORWARD_FOLDS": 3,
    "MODEL_VALIDATION_OVERFIT_WARN_ENABLED": True,
    "MONITORING_ALERTS_ENABLED": False,
    "MONITORING_ALERT_THROTTLE_MINUTES": 30,
    "MONITORING_AUTO_CLEAR_STALE_LOCK": True,
    "MONITORING_AUTO_VALIDATE_STORAGE": True,
    "MONITORING_CONSECUTIVE_FAILURE_THRESHOLD": 3,
    "MONITORING_DATA_FRESHNESS_MAX_AGE_HOURS": 48,
    "MONITORING_DIAGNOSTICS_ENABLED": False,
    "MONITORING_DIR_NAME": 'monitoring',
    "MONITORING_HEARTBEAT_ENABLED": False,
    "MONITORING_HEARTBEAT_MAX_AGE_SECONDS": 1800,
    "MONITORING_SELF_HEALING_ENABLED": False,
    "OPS_BACKUP_DIR_NAME": 'backups',
    "OPS_INCIDENT_RESOLVE_REQUIRES_CONFIRM": True,
    "OPS_JSONL_CHECK_MAX_LINES": 100000,
    "OPS_KEEP_RAW_RESEARCH_DATA": True,
    "OPS_RESTORE_OVERWRITE_REQUIRES_CONFIRM": True,
    "OPS_SCHEMA_VERSION": '1.0',
    "OPS_STORE_CHECK_EXPECTED_FILES": True,
    "OPTIMIZATION_BENCHMARK_NAME": 'buy_and_hold',
    "OPTIMIZATION_COMPARE_BENCHMARK": False,
    "OPTIMIZATION_COMPOSITE_BENCHMARK_WEIGHT": 0.05,
    "OPTIMIZATION_COMPOSITE_CALMAR_WEIGHT": 0.15,
    "OPTIMIZATION_COMPOSITE_DRAWDOWN_WEIGHT": 0.1,
    "OPTIMIZATION_COMPOSITE_PROFIT_FACTOR_WEIGHT": 0.1,
    "OPTIMIZATION_COMPOSITE_RETURN_WEIGHT": 0.25,
    "OPTIMIZATION_COMPOSITE_SHARPE_WEIGHT": 0.2,
    "OPTIMIZATION_COMPOSITE_SORTINO_WEIGHT": 0.15,
    "OPTIMIZATION_MAX_COST_PCT_OF_PROFIT": 50.0,
    "OPTIMIZATION_MIN_PROFIT_FACTOR": 1.0,
    "OPTIMIZATION_MIN_SHARPE": -10.0,
    "OPTIMIZATION_REJECT_SAME_CLOSE_RESEARCH": True,
    "OPTIMIZATION_REPORT_FORMATS": 'json,csv,markdown',
    "OPTIMIZATION_REQUIRE_POSITIVE_RETURN": False,
    "OPTIMIZATION_WF_EXPANDING": False,
    "PORTFOLIO_ALLOCATION_METHOD": 'HYBRID',
    "PORTFOLIO_CORRELATION_LIMIT_ACTION": 'REDUCE',
    "PORTFOLIO_CORRELATION_LOOKBACK_ROWS": 60,
    "PORTFOLIO_CORRELATION_METHOD": 'pearson',
    "PORTFOLIO_DEFAULT_EQUITY": 100000.0,
    "PORTFOLIO_ENABLE_CORRELATION_CHECK": True,
    "PORTFOLIO_EVENT_CONCENTRATION_WARN_COUNT": 3,
    "PORTFOLIO_EVENT_RISK_PENALTY_ENABLED": True,
    "PORTFOLIO_LEDGER_DIR_NAME": 'portfolio_ledger',
    "PORTFOLIO_MAX_PAIRWISE_CORRELATION": 0.8,
    "PORTFOLIO_MIN_ALLOCATION_NOTIONAL": 100.0,
    "PORTFOLIO_RESEARCH_ALLOCATION_METHOD": 'HYBRID',
    "PORTFOLIO_RESEARCH_DIR_NAME": 'portfolio_research',
    "PORTFOLIO_RESEARCH_MAX_ITEMS": 10,
    "PORTFOLIO_RESEARCH_MODE": 'RESEARCH_ONLY',
    "PORTFOLIO_RESEARCH_TARGET_GROSS_EXPOSURE": 1.0,
    "PORTFOLIO_USE_FRACTIONAL_SHARES": False,
    "QA_INCLUDE_MODEL_REGISTRY": True,
    "QA_MODEL_REGISTRY_FAIL_ON_BLOCKED_GOVERNANCE": True,
    "QA_MODEL_REGISTRY_FAIL_ON_MISSING_CARD": False,
    "RELEASE_DIR_NAME": 'release',
    "RELEASE_MIN_PARTIAL_SCORE": 65.0,
    "RELEASE_MIN_READY_SCORE": 85.0,
    "RELEASE_POLICY_DIR_NAME": 'release_policy',
    "RELEASE_REQUIRE_ACCEPTANCE_PASS": False,
    "RELEASE_REQUIRE_QUALITY_PASS": True,
    "RELEASE_REQUIRE_SECURITY_PASS": True,
    "RELEASE_RUN_DOCS_VALIDATION": True,
    "RELEASE_RUN_HEALTHCHECK": True,
    "RELEASE_RUN_PACKAGING": True,
    "RELEASE_RUN_PERFORMANCE_CHECK": True,
    "RELEASE_RUN_QUALITY": True,
    "RELEASE_RUN_REPORT_GENERATION": True,
    "RELEASE_RUN_RUNTIME_DRY_RUN": True,
    "RELEASE_RUN_SCENARIOS": True,
    "RELEASE_RUN_SECURITY": True,
    "RELEASE_SAVE_REPORTS": True,
    "REPORT_INCLUDE_MODEL_REGISTRY": True,
    "RESEARCH_LAB_ALLOW_DESTRUCTIVE": False,
    "RESEARCH_LAB_ALLOW_NETWORK": False,
    "RESEARCH_LAB_ALLOW_TELEGRAM": False,
    "RESEARCH_LAB_DEDUPE_WINDOW_HOURS": 24,
    "RESEARCH_LAB_DEFAULT_MAX_RETRIES": 1,
    "RESEARCH_LAB_DIR_NAME": 'research_lab',
    "RESEARCH_LAB_MAX_JOBS_PER_BATCH": 20,
    "RESEARCH_LAB_MAX_MEMORY_MB": 4096,
    "RESEARCH_LAB_MAX_PARALLEL_JOBS": 1,
    "RESEARCH_LAB_MAX_RUNTIME_SECONDS_PER_BATCH": 3600,
    "RESEARCH_LAB_MAX_RUNTIME_SECONDS_PER_JOB": 900,
    "RESEARCH_LAB_REQUIRE_CONFIRM_FOR_HEAVY_JOBS": True,
    "RESEARCH_LAB_RETRY_BACKOFF_SECONDS": 30,
    "RETENTION_DRIFT_DAYS": 180,
    "RETENTION_KEEP_MIN_COUNT": 10,
    "RETENTION_LOGS_DAYS": 30,
    "RETENTION_REPORTS_DAYS": 180,
    "RETENTION_RESEARCH_LAB_DAYS": 180,
    "RETENTION_SCENARIOS_DAYS": 90,
    "RETENTION_SIGNALS_DAYS": 365,
    "RETENTION_STRESS_DAYS": 180,
    "RETENTION_TEMP_DAYS": 7,
    "REVIEW_DIR_NAME": 'review',
    "REVIEW_PATTERN_MIN_COUNT": 3,
    "REVIEW_WORKFLOW_DIR_NAME": 'review_workflow',
    "RISK_REDUCE_IN_STRESS_REGIME": True,
    "RISK_REJECT_STRESS_REGIME": False,
    "RISK_USE_REGIME_FILTER": False,
    "RUNTIME_BUILD_RESEARCH_PORTFOLIO": False,
    "RUNTIME_INFERENCE_BLOCK_GOVERNANCE_FAIL": False,
    "RUNTIME_INFERENCE_WARN_ON_MODEL_DRIFT": True,
    "RUNTIME_ML_MODEL_ID": '',
    "RUNTIME_PORTFOLIO_ALLOCATION_METHOD": 'HYBRID',
    "RUNTIME_PORTFOLIO_MAX_ITEMS": 10,
    "RUNTIME_REQUIRE_FRESH_DATA": False,
    "RUNTIME_SCHEDULER_FORCE_DRY_RUN_TELEGRAM": True,
    "SCENARIO_SLOW_STEP_SECONDS": 15.0,
    "SCHEMA_VERSION": '1.0.0',
    "SECURITY_ALLOW_UNTRUSTED_MODELS": False,
    "SECURITY_CLI_PREFLIGHT_ENABLED": True,
    "SECURITY_CONFIG_AUDIT_ENABLED": True,
    "SECURITY_MODEL_LOAD_PREFLIGHT_ENABLED": True,
    "SECURITY_NOTIFICATION_PREFLIGHT_ENABLED": True,
    "SECURITY_REDACT_NOTIFICATIONS": True,
    "SECURITY_REPORT_PREFLIGHT_ENABLED": True,
    "SECURITY_WARN_IF_PAPER_DEFAULT_ACTIVE": True,
    "SECURITY_WARN_IF_RUNTIME_TELEGRAM_ACTIVE": False,
    "SECURITY_WARN_IF_SCANNER_PAPER_ENABLED": True,
    "SIGNALS_DIR_NAME": 'signals',
    "SIGNAL_DIGEST_ONLY_BELOW_PRIORITY": 'NORMAL',
    "SIGNAL_EXIT_DEFAULT_STOP_PCT": 4.0,
    "SIGNAL_EXIT_DEFAULT_TARGET_PCT": 8.0,
    "SIGNAL_EXIT_DEFAULT_TIME_STOP_DAYS": 10,
    "SIGNAL_EXIT_REQUIRE_CONFIRM_FOR_MANUAL_OUTCOME": True,
    "SIGNAL_LIFECYCLE_DEFAULT_STATE": 'NEW',
    "SIGNAL_REQUIRE_CONFIRM_FOR_ARCHIVE": True,
    "SIGNAL_REQUIRE_CONFIRM_FOR_MANUAL_STATE_CHANGE": True,
    "SIGNAL_REQUIRE_CONFIRM_FOR_WATCHLIST_REMOVE": True,
    "SIGNAL_STALE_GRACE_MINUTES": 60,
    "SIGNAL_WATCHLIST_DEFAULT_EXPIRY_DAYS": 14,
    "STRATEGY_ALLOW_CANDIDATE_IN_SCANNER": False,
    "STRATEGY_ALLOW_DEGRADED_IN_SCANNER": False,
    "STRATEGY_GATE_BEFORE_ADAPTIVE": True,
    "STRATEGY_GATE_BEFORE_ENSEMBLE": True,
    "STRATEGY_GATE_BEFORE_SCANNER": True,
    "STRATEGY_REGISTRY_REQUIRE_CONFIRM_FOR_REGISTER": True,
    "STRATEGY_REGISTRY_REQUIRE_CONFIRM_FOR_STATUS_CHANGE": True,
    "STRATEGY_SCORE_MIN_VALIDATED": 70.0,
    "STRATEGY_SCORE_WEIGHT_BACKTEST": 0.1,
    "STRATEGY_SCORE_WEIGHT_DRIFT": 0.1,
    "STRATEGY_SCORE_WEIGHT_EXECUTION": 0.1,
    "STRATEGY_SCORE_WEIGHT_GOVERNANCE": 0.05,
    "STRATEGY_SCORE_WEIGHT_MONTE_CARLO": 0.2,
    "STRATEGY_SCORE_WEIGHT_OVERFIT": 0.15,
    "STRATEGY_SCORE_WEIGHT_REVIEW": 0.05,
    "STRATEGY_SCORE_WEIGHT_VALIDATION": 0.25,
    "TELEGRAM_ENABLED": False,
    "VALIDATION_DIR_NAME": 'validation',
    "WHATIF_INCLUDE_BASELINE": True,
    "WHATIF_RANKING_METRIC": 'estimated_net_quality_score',
    "WHATIF_SENSITIVITY_DELTA_FAIL_PCT": 30.0,
    "WHATIF_SENSITIVITY_DELTA_WARN_PCT": 15.0,
    "INTRADAY_FETCH_BATCH_SIZE": 20,
    "DAILY_HISTORY_PERIOD": "10y",
    "DAILY_FETCH_BATCH_SIZE": 20,
    "DAILY_MIN_REQUEST_INTERVAL_SECONDS": 1.0,
    "DAILY_STALE_DAYS": 5,
    "INTRADAY_MIN_REQUEST_INTERVAL_SECONDS": 1.0,
    "INTRADAY_BACKOFF_BASE_SECONDS": 2.0,
    "INTRADAY_MAX_RETRIES": 4,
    "INTRADAY_ARCHIVE_OVERLAP_BARS": 2,
    "INTRADAY_UNIVERSE_DELIST_MISSES": 10,
    "INTRADAY_UNIVERSE_AUTO_SYNC": True,
    "RUNTIME_UNIVERSE_AUTO_SYNC": False,  # runtime DATA_REFRESH never hits the network for universe sync unless explicitly enabled
    "INTRADAY_UNIVERSE_MIN_LISTING": 300,
    "INTRADAY_UNIVERSE_IPO_DAYS": 90,
    "INTRADAY_DATA_DELAY_MINUTES": 15,
    "INTRADAY_MAX_LAG_BARS": 2,
    "INTRADAY_COMMISSION_BPS": 5.0,
    "INTRADAY_BSMV_RATE": 0.05,
    "INTRADAY_EXCHANGE_FEE_BPS": 0.3,
    "INTRADAY_SLIPPAGE_IMPACT_COEF": 0.1,
    "INTRADAY_MAX_PARTICIPATION": 0.05,
    "CASH_BENCHMARK_ANNUAL_RATE": 0.37,  # policy rate proxy (TCMB 37%, 2026-09); separate from PAPER_CASH_INTEREST_ANNUAL deposit placeholder
    "CASH_BENCHMARK_WITHHOLDING": 0.0,  # benchmark gross by default; set 0.15 to see after-stopaj (unverified)
    "DAILY_COST_COMMISSION_PLACEHOLDER_BPS": 5.0,  # placeholder-commission scenario per leg; zero_commission scenario uses 0
    "DAILY_COST_EXCHANGE_FEE_BPS": 0.3,  # exchange+takas share per leg (placeholder, verify)
    "DAILY_COST_BSMV_RATE": 0.05,  # BSMV on commission only (0 cost when commission is 0)
    "DAILY_COST_IMPACT_COEF": 0.5,  # sqrt impact coef for daily events: bps = coef*100*sqrt(order/ADV)
    "DAILY_COST_MAX_PARTICIPATION": 0.05,  # max share of ADV per order; above -> NaN (disallowed)
    "INTRADAY_ALLOW_SHORT": False,
    "DAILY_CAPITAL_TRY": 100000.0,  # cross-sectional daily research: capital (order_value = capital/top_n)
    "DAILY_TOP_N": 8,  # long-only max positions
    "DAILY_MIN_ADV_TRY": 5000000.0,  # point-in-time universe: ADV20 floor (TRY)
    "DAILY_ADV_WINDOW": 20,
    "DAILY_MIN_HISTORY_DAYS": 60,  # min bars of history before a symbol is eligible
    "DAILY_MIN_PRICE_TRY": 1.0,
    "DAILY_LEGACY_SEMANTICS": False,  # True = reproduce pre-audit daily results (flat 10% limit, no fill/lock/health rules, spread proxy 0)
    "DAILY_ENTRY_FILL_POLICY": "cash",  # unfillable entry (open>=limit-up, H==L lock, zero volume): cash | next_ranked | flag | off
    "DAILY_EXIT_LOCK_DEFER": True,  # exit on a locked limit-down close is deferred to the first unlocked session
    "DAILY_NAN_EXIT_CARRY": True,  # exit close NaN (halt) -> carry to the next available close instead of dropping the name
    "DAILY_BAR_HEALTH": True,  # causal bar health mask (bad bars removed from universe_mask)
    "DAILY_BAR_HEALTH_TOL": 0.005,  # tolerance added to the price limit when checking close-to-close / gap moves
    "DAILY_BAR_SPIKE_PCT": 0.08,  # spike-and-revert detector threshold (|move| and opposite move next session)
    "PRICE_LIMIT_SCHEDULE": "",  # "YYYY-MM-DD:pct,..." override; empty = sessions.PRICE_LIMIT_SCHEDULE (UNVERIFIED history, confirm with Borsa Istanbul)
    "DAILY_COST_SPREAD_PROXY_BPS_BASE": 1.0,  # half-spread proxy = base + k/sqrt(ADV/1e6 TRY) bps (placeholder, unverified); floored by the tick spread
    "DAILY_COST_SPREAD_PROXY_K_BPS": 3.0,  # k in the ADV-dependent half-spread proxy; 0 and base 0 = legacy
    "DAILY_OVERLAY_MAX_DD": 0.2,  # psychological max drawdown (fraction); overlay is fully in cash at this DD. NOTE: DailyLossGuard uses RISK_MAX_DRAWDOWN_PCT (percent, intraday paper guard, 8.0) - set it >= 100*this for the multi-day book
    "DAILY_OVERLAY_DERISK_START_FRAC": 0.5,  # start de-risking at this fraction of max DD
    "DAILY_OVERLAY_FLOOR_FRAC": 0.75,  # exposure = DAILY_OVERLAY_FLOOR_EXPOSURE at this fraction of max DD
    "DAILY_OVERLAY_FLOOR_EXPOSURE": 0.25,  # exposure at the floor fraction of max DD (linear to 0 at max DD)
    "DAILY_OVERLAY_HYSTERESIS": 0.02,  # DD must improve by this (absolute) before exposure is raised again
    "DAILY_OVERLAY_RECOVER_REBOUND_FRAC": 0.5,  # re-entry after halt: shadow strategy rebounded by this fraction of max DD from its trough
    "DAILY_OVERLAY_MIN_HALT_DAYS": 10,  # min sessions in cash after a halt
    "DAILY_OVERLAY_MAX_HALT_DAYS": 60,  # force re-entry (ramped) after this many sessions in cash
    "DAILY_OVERLAY_RAMP_DAYS": 10,  # sessions to ramp exposure back after re-entry
    "DAILY_OVERLAY_TARGET_VOL": 0.25,  # annualised vol target of the strategy sleeve (scale=min(1,target/realised))
    "DAILY_OVERLAY_VOL_WINDOW": 20,  # sessions for realised vol (uses data up to t-1)
    "DAILY_OVERLAY_MISSING_REGIME_SCALE": 1.0,  # regime scale before the first valid regime value (warm-up); same as runner regime_fill
    "DAILY_PER_NAME_CAP": 0.25,  # max weight per name when sizing lots
    "DAILY_MIN_ORDER_VALUE_TRY": 500.0,  # orders below this TRY value are dropped to cash (placeholder)
    "REAL_REPORT_TARGET_REAL_CAGR": 0.75,  # user target: real (CPI-adjusted) CAGR
    "REAL_REPORT_DEPOSIT_WITHHOLDING": 0.15,  # stopaj on deposit interest for the cash comparator in real reports (unverified placeholder)
    "REAL_REPORT_CPI_LAG_MONTHS": 1,  # CPI publication lag (months) used in causal mode
    # Robustness layer (v2 candidacy; stacked ON TOP of the gate, tightening only). Fixed a priori, NOT tuned to results.
    "EDGE_ROBUST_TRIM_EVENT_FRAC": 0.05,  # (a) drop the best 5% of events by net excess return: mean must stay > 0
    "EDGE_ROBUST_DROP_TOP_SYMBOLS": 10,  # (b) drop the 10 top-contributing symbols ...
    "EDGE_ROBUST_MIN_REMAINING_SHARPE_FRAC": 0.30,  # ... remaining excess Sharpe must be > 0 and >= 30% of original
    "EDGE_ROBUST_YEAR_MIN_LIVE_DAYS": 60,  # (c) a calendar year counts only with >= 60 live days
    "EDGE_ROBUST_YEAR_MIN_POSITIVE_FRAC": 0.60,  # (c) >= 60% of counted years with positive excess
    "EDGE_ROBUST_YEAR_MAX_SHARE": 0.60,  # (c) no single year > 60% of total excess
    "EDGE_ROBUST_COST_STRESS_MULT": 2.0,  # (d) excess Sharpe must stay > 0 with trading costs multiplied by this
    "EDGE_ROBUST_EVENT_CAP": 0.20,  # (e) winsorise event net excess at +20%: mean must stay > 0
    "EDGE_ROBUST_BREADTH_TOP_K": 20,  # (f) informational breadth check (top-20 basket), non-gating
    "EDGE_ROBUST_GLOBAL_MAD_K": 3.5,  # (g) MAD trimming constant for the global-DSR Sharpe-dispersion pool
    "EDGE_GATE_MIN_EVENTS": 300,
    "EDGE_GATE_MIN_ACTIVE_DAYS": 60,
    "EDGE_GATE_DSR_MIN": 0.95,
    "EDGE_GATE_PBO_MAX": 0.25,
    "EDGE_GATE_FDR_ALPHA": 0.05,
    "EDGE_GATE_REALITY_CHECK_ALPHA": 0.05,
    "EDGE_GATE_MIN_POSITIVE_PATH_FRACTION": 0.7,
    "EDGE_GATE_CI_ALPHA": 0.05,
    "EDGE_GATE_EMBARGO_DAYS": 1,
    "EDGE_NOTIONAL_TRY": 10000.0,
    "EDGE_MIN_AVG_DAILY_VALUE_TRY": 5000000.0,
    "MODEL_LOOP_HORIZON_BARS": 4,
    "MODEL_LOOP_PROB_THRESHOLD": 0.55,
    "MODEL_LOOP_MIN_TRAIN_EVENTS": 2000,
    "MODEL_LOOP_KIND": "hgb",
    "MODEL_LOOP_SEED": 42,
    "MODEL_LOOP_PSI_WARN": 0.1,
    "MODEL_LOOP_PSI_ALERT": 0.25,
    "MODEL_LOOP_KS_ALPHA": 0.01,
    "MODEL_LOOP_ADWIN_DELTA": 0.002,
    "MODEL_LOOP_MIN_DAYS_BETWEEN_RETRAIN": 5,
    "MODEL_LOOP_MIN_CHALLENGER_IMPROVEMENT": 0.0,
    "MODEL_LOOP_FEATURE_ALERT_FRAC": 0.2,
    "MODEL_LOOP_AUTO_ENABLE_RUNTIME": True,
    # --- forward shadow paper trading (forward/); simulation only, no real order is ever sent ---
    "FORWARD_PORTFOLIOS": "",  # "" = auto-freeze best-by-ledger per family; else JSON list of {family, params, horizon, top_n}
    "FORWARD_HORIZONS": "5,10",  # horizons frozen per family at registration time
    "FORWARD_TOP_N": 8,
    "FORWARD_TIER_OVERRIDES": '{"ml_xs_hgb|5": "watch"}',  # audit: ml_xs_hgb h5 CANDIDATE is a batch-order artefact (global pool n=26->310, global_dsr 0.17) -> tier watch
    "FORWARD_N_CONTROLS": 6,  # control-tier rule/ML portfolios (best v2 excess Sharpe per family, not CANDIDATE)
    "FORWARD_PLACEBO_SEED": 20261010,  # seed of the random-score placebo shadow portfolios (frozen in portfolios file)
    "FORWARD_CAPITAL_TRY": 100000.0,  # simulated NAV per portfolio (integer-share lots)
    "FORWARD_MAX_LAG_SESSIONS": 0,  # decision gate: newest bar may lag the expected session by at most N sessions
    "FORWARD_ALERT_STALE_SESSIONS": 1,  # monitoring alert when data lags more than N sessions
    "FORWARD_SESSION_READY_TIME": "18:30",  # Istanbul time after which today's daily bar counts as complete (close 18:00 + 15 min delay)
    "FORWARD_MIN_LIVE_DAYS": 60,  # no verdict before this many live trading days (INSUFFICIENT)
    "FORWARD_MIN_CALENDAR_DAYS": 90,  # planned minimum observation window (3 months)
    "FORWARD_MIN_TSTAT": 2.0,  # floor for the Newey-West excess t-stat (multiplicity-adjusted critical value is also required)
    "FORWARD_MIN_COVERAGE": 0.8,  # decision gate: share of symbols that must have the newest bar
    "FORWARD_MIN_BASKETS": 6,  # closed baskets needed for a verdict
    "FORWARD_MAX_DD_PASS": 0.20,
    "FORWARD_DD_ALERT_LEVELS": "0.10,0.15,0.20",
    "FORWARD_RUN_HOUR": 19,  # scheduler: Europe/Istanbul, trading days
    "FORWARD_RUN_MINUTE": 30,
    "FORWARD_CATCHUP_HOUR": 8,
    "FORWARD_CATCHUP_MINUTE": 30,
}
