from pydantic import BaseModel, Field

class Settings(BaseModel):
    ENABLE_FINAL_HANDOFF: bool = True
    FINAL_HANDOFF_DIR_NAME: str = "final_handoff"
    FINAL_HANDOFF_RESEARCH_ONLY: bool = True
    FINAL_HANDOFF_SAVE_RESULTS: bool = True
    FINAL_HANDOFF_BUILD_RELEASE_PACK: bool = True
    FINAL_HANDOFF_RELEASE_PACK_STAGE: str = "BUILT"
    FINAL_HANDOFF_INCLUDE_DOCS: bool = True
    FINAL_HANDOFF_INCLUDE_EXAMPLES: bool = True
    FINAL_HANDOFF_INCLUDE_REPORTS: bool = True
    FINAL_HANDOFF_INCLUDE_MANIFESTS: bool = True
    FINAL_HANDOFF_INCLUDE_CHECKSUMS: bool = True
    FINAL_HANDOFF_BUILD_OPERATOR_PLAYBOOK: bool = True
    FINAL_HANDOFF_BUILD_DEVELOPER_PLAYBOOK: bool = True
    FINAL_HANDOFF_BUILD_COMMAND_MAP: bool = True
    FINAL_HANDOFF_BUILD_MODULE_MAP: bool = True
    FINAL_HANDOFF_BUILD_ROADMAP: bool = True
    FINAL_HANDOFF_BUILD_MAINTENANCE_TASKS: bool = True
    FINAL_HANDOFF_INCLUDE_PHASE_101_PLUS_ROADMAP: bool = True
    FINAL_HANDOFF_ROADMAP_DEFAULT_PRIORITY: str = "MEDIUM"
    FINAL_HANDOFF_DAILY_ROUTINE_ENABLED: bool = True
    FINAL_HANDOFF_WEEKLY_ROUTINE_ENABLED: bool = True
    FINAL_HANDOFF_MONTHLY_ROUTINE_ENABLED: bool = True
    RUNTIME_FINAL_HANDOFF_ENABLED: bool = True
    QA_INCLUDE_FINAL_HANDOFF: bool = True
    OPS_INCLUDE_FINAL_HANDOFF: bool = True
    REPORT_INCLUDE_FINAL_HANDOFF: bool = True
    RESEARCH_AUTO_LOG_FINAL_HANDOFF: bool = False

def get_settings():
    return Settings()
