
class AuditEvents:
    PERFORMANCE_PROFILE_CREATED = "PERFORMANCE_PROFILE_CREATED"
    RESOURCE_BUDGET_EVALUATED = "RESOURCE_BUDGET_EVALUATED"
    CACHE_ENTRY_CREATED = "CACHE_ENTRY_CREATED"
    CACHE_ENTRY_INVALIDATED = "CACHE_ENTRY_INVALIDATED"
    PERFORMANCE_BENCHMARK_RUN = "PERFORMANCE_BENCHMARK_RUN"
    BOTTLENECKS_ANALYZED = "BOTTLENECKS_ANALYZED"
    PERFORMANCE_REGRESSION_DETECTED = "PERFORMANCE_REGRESSION_DETECTED"
    PERFORMANCE_REPORT_CREATED = "PERFORMANCE_REPORT_CREATED"
