DEFAULT_MARKET = "BIST"
DEFAULT_CURRENCY = "TRY"
DEFAULT_TIMEZONE = "Europe/Istanbul"
YFINANCE_BIST_SUFFIX = ".IS"
INTERNAL_SYMBOL_PATTERN = r"^[A-Z0-9]+$"

BIST_MARKET_OPEN_TIME = "10:00"
BIST_MARKET_CLOSE_TIME = "18:00"
