with open("bist_signal_bot/core/audit.py", "r") as f:
    content = f.read()

drift_events = """    DRIFT_ANALYSIS_STARTED = "DRIFT_ANALYSIS_STARTED"
    DRIFT_ANALYSIS_COMPLETED = "DRIFT_ANALYSIS_COMPLETED"
    DRIFT_ANALYSIS_FAILED = "DRIFT_ANALYSIS_FAILED"
    FEATURE_DRIFT_DETECTED = "FEATURE_DRIFT_DETECTED"
    MODEL_DRIFT_DETECTED = "MODEL_DRIFT_DETECTED"
    CALIBRATION_REPORT_CREATED = "CALIBRATION_REPORT_CREATED"
    SIGNAL_DECAY_ANALYZED = "SIGNAL_DECAY_ANALYZED"
    STRATEGY_DECAY_ANALYZED = "STRATEGY_DECAY_ANALYZED"
    PORTFOLIO_DRIFT_ANALYZED = "PORTFOLIO_DRIFT_ANALYZED"
    DRIFT_REFERENCE_CREATED = "DRIFT_REFERENCE_CREATED"
    DRIFT_RESULT_SAVED = "DRIFT_RESULT_SAVED"
"""

if "DRIFT_ANALYSIS_STARTED" not in content:
    content = content.replace('    SECURITY_THREAT_DETECTED = "SECURITY_THREAT_DETECTED"', '    SECURITY_THREAT_DETECTED = "SECURITY_THREAT_DETECTED"\n' + drift_events)

with open("bist_signal_bot/core/audit.py", "w") as f:
    f.write(content)
